// biu_reg.h 8-30-2011
// gen_biu Ver 1.0 generated by  
#define xd_p_eagle_reg_lnk2ofdm_data_63_56	(*(volatile byte xdata *) 0xF6A7)
#define    p_eagle_reg_lnk2ofdm_data_63_56	0xF6A7 
#define	eagle_reg_lnk2ofdm_data_63_56_pos 0
#define	eagle_reg_lnk2ofdm_data_63_56_len 8
#define	eagle_reg_lnk2ofdm_data_63_56_lsb 56

#define xd_p_eagle_reg_fec_sw_rst	(*(volatile byte xdata *) 0xF702)
#define    p_eagle_reg_fec_sw_rst	0xF702 
#define	eagle_reg_fec_sw_rst_pos 0
#define	eagle_reg_fec_sw_rst_len 1
#define	eagle_reg_fec_sw_rst_lsb 0
#define xd_p_eagle_reg_tps_gi	(*(volatile byte xdata *) 0xF725)
#define    p_eagle_reg_tps_gi	0xF725 
#define	eagle_reg_tps_gi_pos 0
#define	eagle_reg_tps_gi_len 2
#define	eagle_reg_tps_gi_lsb 0

#define xd_p_eagle_reg_iqik_c1_7_0	(*(volatile byte xdata *) 0xF752)
#define    p_eagle_reg_iqik_c1_7_0	0xF752 
#define	eagle_reg_iqik_c1_7_0_pos 0
#define	eagle_reg_iqik_c1_7_0_len 8
#define	eagle_reg_iqik_c1_7_0_lsb 0
#define xd_p_eagle_reg_iqik_c1_10_8	(*(volatile byte xdata *) 0xF753)
#define    p_eagle_reg_iqik_c1_10_8	0xF753 
#define	eagle_reg_iqik_c1_10_8_pos 0
#define	eagle_reg_iqik_c1_10_8_len 3
#define	eagle_reg_iqik_c1_10_8_lsb 8
#define xd_p_eagle_reg_iqik_c2_7_0	(*(volatile byte xdata *) 0xF754)
#define    p_eagle_reg_iqik_c2_7_0	0xF754 
#define	eagle_reg_iqik_c2_7_0_pos 0
#define	eagle_reg_iqik_c2_7_0_len 8
#define	eagle_reg_iqik_c2_7_0_lsb 0
#define xd_p_eagle_reg_iqik_c2_10_8	(*(volatile byte xdata *) 0xF755)
#define    p_eagle_reg_iqik_c2_10_8	0xF755 
#define	eagle_reg_iqik_c2_10_8_pos 0
#define	eagle_reg_iqik_c2_10_8_len 3
#define	eagle_reg_iqik_c2_10_8_lsb 8
#define xd_p_eagle_reg_iqik_c3_7_0	(*(volatile byte xdata *) 0xF756)
#define    p_eagle_reg_iqik_c3_7_0	0xF756 
#define	eagle_reg_iqik_c3_7_0_pos 0
#define	eagle_reg_iqik_c3_7_0_len 8
#define	eagle_reg_iqik_c3_7_0_lsb 0
#define xd_p_eagle_reg_iqik_c3_10_8	(*(volatile byte xdata *) 0xF757)
#define    p_eagle_reg_iqik_c3_10_8	0xF757 
#define	eagle_reg_iqik_c3_10_8_pos 0
#define	eagle_reg_iqik_c3_10_8_len 3
#define	eagle_reg_iqik_c3_10_8_lsb 8

#define    p_eagle_reg_iqik_dc_i_7_0 0xF763
#define    p_eagle_reg_iqik_dc_i_8	 0xF764 
#define    p_eagle_reg_iqik_dc_q_7_0 0xF765 
#define    p_eagle_reg_iqik_dc_q_8	 0xF766 

#define xd_I2C_eagle_reg_ofdm_rst	(*(volatile byte xdata *) 0xF957)
#define    I2C_eagle_reg_ofdm_rst	0xF957 
#define	eagle_reg_ofdm_rst_pos 1
#define	eagle_reg_ofdm_rst_len 1
#define	eagle_reg_ofdm_rst_lsb 0
#define xd_I2C_eagle_reg_ofdm_rst_en	(*(volatile byte xdata *) 0xF957)
#define    I2C_eagle_reg_ofdm_rst_en	0xF957 
#define	eagle_reg_ofdm_rst_en_pos 4
#define	eagle_reg_ofdm_rst_en_len 1
#define	eagle_reg_ofdm_rst_en_lsb 0
#define xd_p_reg_psi_access	(*(volatile byte xdata *) 0xF980)
#define    p_reg_psi_access	0xF980 
#define	reg_psi_access_pos 0
#define	reg_psi_access_len 1
#define	reg_psi_access_lsb 0
#define xd_p_reg_psi_dat	(*(volatile byte xdata *) 0xF981)
#define    p_reg_psi_dat	0xF981 
#define	reg_psi_dat_pos 0
#define	reg_psi_dat_len 8
#define	reg_psi_dat_lsb 0
#define xd_p_reg_psi_index	(*(volatile byte xdata *) 0xF982)
#define    p_reg_psi_index	0xF982 
#define	reg_psi_index_pos 0
#define	reg_psi_index_len 8
#define	reg_psi_index_lsb 0
#define xd_p_mp2if_mpeg_ser_do7	(*(volatile byte xdata *) 0xF984)
#define    p_mp2if_mpeg_ser_do7	0xF984 
#define	mp2if_mpeg_ser_do7_pos 0
#define	mp2if_mpeg_ser_do7_len 1
#define	mp2if_mpeg_ser_do7_lsb 0
#define xd_p_mp2if_mpeg_ser_mode	(*(volatile byte xdata *) 0xF985)
#define    p_mp2if_mpeg_ser_mode	0xF985 
#define	mp2if_mpeg_ser_mode_pos 0
#define	mp2if_mpeg_ser_mode_len 1
#define	mp2if_mpeg_ser_mode_lsb 0
#define xd_p_mp2if_mpeg_par_mode	(*(volatile byte xdata *) 0xF986)
#define    p_mp2if_mpeg_par_mode	0xF986 
#define	mp2if_mpeg_par_mode_pos 0
#define	mp2if_mpeg_par_mode_len 1
#define	mp2if_mpeg_par_mode_lsb 0
#define xd_p_eagle_reg_mpeg_full_speed	(*(volatile byte xdata *) 0xF990)
#define    p_eagle_reg_mpeg_full_speed	0xF990 
#define	eagle_reg_mpeg_full_speed_pos 0
#define	eagle_reg_mpeg_full_speed_len 1
#define	eagle_reg_mpeg_full_speed_lsb 0
#define xd_p_mp2if_pid_complement	(*(volatile byte xdata *) 0xF991)
#define    p_mp2if_pid_complement	0xF991 
#define	mp2if_pid_complement_pos 0
#define	mp2if_pid_complement_len 1
#define	mp2if_pid_complement_lsb 0
#define xd_p_mp2if_pid_rst	(*(volatile byte xdata *) 0xF992)
#define    p_mp2if_pid_rst	0xF992 
#define	mp2if_pid_rst_pos 0
#define	mp2if_pid_rst_len 1
#define	mp2if_pid_rst_lsb 0
#define xd_p_mp2if_pid_en	(*(volatile byte xdata *) 0xF993)
#define    p_mp2if_pid_en	0xF993 
#define	mp2if_pid_en_pos 0
#define	mp2if_pid_en_len 1
#define	mp2if_pid_en_lsb 0
#define xd_p_mp2if_pid_index_en	(*(volatile byte xdata *) 0xF994)
#define    p_mp2if_pid_index_en	0xF994 
#define	mp2if_pid_index_en_pos 0
#define	mp2if_pid_index_en_len 1
#define	mp2if_pid_index_en_lsb 0
#define xd_p_mp2if_pid_index	(*(volatile byte xdata *) 0xF995)
#define    p_mp2if_pid_index	0xF995 
#define	mp2if_pid_index_pos 0
#define	mp2if_pid_index_len 5
#define	mp2if_pid_index_lsb 0
#define xd_p_mp2if_pid_index	(*(volatile byte xdata *) 0xF995)
#define    p_mp2if_pid_index	0xF995 
#define	mp2if_pid_index_pos 0
#define	mp2if_pid_index_len 5
#define	mp2if_pid_index_lsb 0
#define xd_p_mp2if_pid_dat_l	(*(volatile byte xdata *) 0xF996)
#define    p_mp2if_pid_dat_l	0xF996 
#define	mp2if_pid_dat_l_pos 0
#define	mp2if_pid_dat_l_len 8
#define	mp2if_pid_dat_l_lsb 0
#define xd_p_mp2if_pid_dat_h	(*(volatile byte xdata *) 0xF997)
#define    p_mp2if_pid_dat_h	0xF997 
#define	mp2if_pid_dat_h_pos 0
#define	mp2if_pid_dat_h_len 5
#define	mp2if_pid_dat_h_lsb 0
#define xd_p_eagle_reg_mp2_sw_rst	(*(volatile byte xdata *) 0xF99D)
#define    p_eagle_reg_mp2_sw_rst	0xF99D 
#define	eagle_reg_mp2_sw_rst_pos 0
#define	eagle_reg_mp2_sw_rst_len 1
#define	eagle_reg_mp2_sw_rst_lsb 0
#define xd_p_eagle_reg_mp2if2_en	(*(volatile byte xdata *) 0xF9A3)
#define    p_eagle_reg_mp2if2_en	0xF9A3 
#define	eagle_reg_mp2if2_en_pos 0
#define	eagle_reg_mp2if2_en_len 1
#define	eagle_reg_mp2if2_en_lsb 0
#define xd_p_eagle_reg_mp2if2_sw_rst	(*(volatile byte xdata *) 0xF9A4)
#define    p_eagle_reg_mp2if2_sw_rst	0xF9A4 
#define	eagle_reg_mp2if2_sw_rst_pos 0
#define	eagle_reg_mp2if2_sw_rst_len 1
#define	eagle_reg_mp2if2_sw_rst_lsb 0
#define xd_p_eagle_reg_mp2if2_half_psb	(*(volatile byte xdata *) 0xF9A5)
#define    p_eagle_reg_mp2if2_half_psb	0xF9A5 
#define	eagle_reg_mp2if2_half_psb_pos 0
#define	eagle_reg_mp2if2_half_psb_len 1
#define	eagle_reg_mp2if2_half_psb_lsb 0
#define xd_p_eagle_reg_mp2if_stop_en	(*(volatile byte xdata *) 0xF9B5)
#define    p_eagle_reg_mp2if_stop_en	0xF9B5 
#define	eagle_reg_mp2if_stop_en_pos 0
#define	eagle_reg_mp2if_stop_en_len 1
#define	eagle_reg_mp2if_stop_en_lsb 0
#define xd_p_eagle_reg_sys_buf_overflow	(*(volatile byte xdata *) 0xF9B9)
#define    p_eagle_reg_sys_buf_overflow	0xF9B9 
#define	eagle_reg_sys_buf_overflow_pos 0
#define	eagle_reg_sys_buf_overflow_len 1
#define	eagle_reg_sys_buf_overflow_lsb 0
#define xd_p_eagle_reg_tsip_en	(*(volatile byte xdata *) 0xF9CC)
#define    p_eagle_reg_tsip_en	0xF9CC 
#define	eagle_reg_tsip_en_pos 0
#define	eagle_reg_tsip_en_len 1
#define	eagle_reg_tsip_en_lsb 0
#define xd_p_eagle_reg_tsis_en	(*(volatile byte xdata *) 0xF9CD)
#define    p_eagle_reg_tsis_en	0xF9CD 
#define	eagle_reg_tsis_en_pos 0
#define	eagle_reg_tsis_en_len 1
#define	eagle_reg_tsis_en_lsb 0
#define xd_p_eagle_reg_ts_in_src	(*(volatile byte xdata *) 0xF9D8)
#define    p_eagle_reg_ts_in_src	0xF9D8 
#define	eagle_reg_ts_in_src_pos 0
#define	eagle_reg_ts_in_src_len 1
#define	eagle_reg_ts_in_src_lsb 0

#define eagle_reg_tx_fifo_overflow	0xF9E7

#define xd_p_eagle_reg_afe_mem0	(*(volatile byte xdata *) 0xFB24)
#define    p_eagle_reg_afe_mem0	0xFB24 
#define	eagle_reg_afe_mem0_pos 0
#define	eagle_reg_afe_mem0_len 8
#define	eagle_reg_afe_mem0_lsb 0
#define xd_p_eagle_reg_afe_mem1	(*(volatile byte xdata *) 0xFB25)
#define    p_eagle_reg_afe_mem1	0xFB25 
#define	eagle_reg_afe_mem1_pos 0
#define	eagle_reg_afe_mem1_len 8
#define	eagle_reg_afe_mem1_lsb 0

#define xd_p_eagle_reg_dyn0_clk	(*(volatile byte xdata *) 0xFBA8)
#define    p_eagle_reg_dyn0_clk	0xFBA8 
#define	eagle_reg_dyn0_clk_pos 0
#define	eagle_reg_dyn0_clk_len 1
#define	eagle_reg_dyn0_clk_lsb 0
// biu_reg.h 6-29-2010
// gen_biu Ver 1.0 generated by weili.su 
#define xd_r_io_mux_pwron_clk_strap	(*(volatile byte xdata *) 0xD800)
#define    r_io_mux_pwron_clk_strap	0xD800 
#define	io_mux_pwron_clk_strap_pos 0
#define	io_mux_pwron_clk_strap_len 4
#define	io_mux_pwron_clk_strap_lsb 0
#define xd_r_io_mux_pwron_mode_strap	(*(volatile byte xdata *) 0xD801)
#define    r_io_mux_pwron_mode_strap	0xD801 
#define	io_mux_pwron_mode_strap_pos 0
#define	io_mux_pwron_mode_strap_len 4
#define	io_mux_pwron_mode_strap_lsb 0
#define xd_p_eagle_reg_top_padmiscdr2	(*(volatile byte xdata *) 0xD830)
#define    p_eagle_reg_top_padmiscdr2	0xD830 
#define	eagle_reg_top_padmiscdr2_pos 0
#define	eagle_reg_top_padmiscdr2_len 1
#define	eagle_reg_top_padmiscdr2_lsb 0
#define xd_p_eagle_reg_top_padmiscdr4	(*(volatile byte xdata *) 0xD831)
#define    p_eagle_reg_top_padmiscdr4	0xD831 
#define	eagle_reg_top_padmiscdr4_pos 0
#define	eagle_reg_top_padmiscdr4_len 1
#define	eagle_reg_top_padmiscdr4_lsb 0
#define xd_p_eagle_reg_top_padmiscdr8	(*(volatile byte xdata *) 0xD832)
#define    p_eagle_reg_top_padmiscdr8	0xD832 
#define	eagle_reg_top_padmiscdr8_pos 0
#define	eagle_reg_top_padmiscdr8_len 1
#define	eagle_reg_top_padmiscdr8_lsb 0
#define xd_p_eagle_reg_top_padmiscdrsr	(*(volatile byte xdata *) 0xD833)
#define    p_eagle_reg_top_padmiscdrsr	0xD833 
#define	eagle_reg_top_padmiscdrsr_pos 0
#define	eagle_reg_top_padmiscdrsr_len 1
#define	eagle_reg_top_padmiscdrsr_lsb 0
#define xd_r_eagle_reg_top_gpioh1_i	(*(volatile byte xdata *) 0xD8AE)
#define    r_eagle_reg_top_gpioh1_i	0xD8AE 
#define	eagle_reg_top_gpioh1_i_pos 0
#define	eagle_reg_top_gpioh1_i_len 1
#define	eagle_reg_top_gpioh1_i_lsb 0
#define xd_p_eagle_reg_top_gpioh1_o	(*(volatile byte xdata *) 0xD8AF)
#define    p_eagle_reg_top_gpioh1_o	0xD8AF 
#define	eagle_reg_top_gpioh1_o_pos 0
#define	eagle_reg_top_gpioh1_o_len 1
#define	eagle_reg_top_gpioh1_o_lsb 0
#define xd_p_eagle_reg_top_gpioh1_en	(*(volatile byte xdata *) 0xD8B0)
#define    p_eagle_reg_top_gpioh1_en	0xD8B0 
#define	eagle_reg_top_gpioh1_en_pos 0
#define	eagle_reg_top_gpioh1_en_len 1
#define	eagle_reg_top_gpioh1_en_lsb 0
#define xd_p_eagle_reg_top_gpioh1_on	(*(volatile byte xdata *) 0xD8B1)
#define    p_eagle_reg_top_gpioh1_on	0xD8B1 
#define	eagle_reg_top_gpioh1_on_pos 0
#define	eagle_reg_top_gpioh1_on_len 1
#define	eagle_reg_top_gpioh1_on_lsb 0
#define xd_r_eagle_reg_top_gpioh3_i	(*(volatile byte xdata *) 0xD8B2)
#define    r_eagle_reg_top_gpioh3_i	0xD8B2 
#define	eagle_reg_top_gpioh3_i_pos 0
#define	eagle_reg_top_gpioh3_i_len 1
#define	eagle_reg_top_gpioh3_i_lsb 0
#define xd_p_eagle_reg_top_gpioh3_o	(*(volatile byte xdata *) 0xD8B3)
#define    p_eagle_reg_top_gpioh3_o	0xD8B3 
#define	eagle_reg_top_gpioh3_o_pos 0
#define	eagle_reg_top_gpioh3_o_len 1
#define	eagle_reg_top_gpioh3_o_lsb 0
#define xd_p_eagle_reg_top_gpioh3_en	(*(volatile byte xdata *) 0xD8B4)
#define    p_eagle_reg_top_gpioh3_en	0xD8B4 
#define	eagle_reg_top_gpioh3_en_pos 0
#define	eagle_reg_top_gpioh3_en_len 1
#define	eagle_reg_top_gpioh3_en_lsb 0
#define xd_p_eagle_reg_top_gpioh3_on	(*(volatile byte xdata *) 0xD8B5)
#define    p_eagle_reg_top_gpioh3_on	0xD8B5 
#define	eagle_reg_top_gpioh3_on_pos 0
#define	eagle_reg_top_gpioh3_on_len 1
#define	eagle_reg_top_gpioh3_on_lsb 0
#define xd_r_eagle_reg_top_gpioh2_i	(*(volatile byte xdata *) 0xD8B6)
#define    r_eagle_reg_top_gpioh2_i	0xD8B6 
#define	eagle_reg_top_gpioh2_i_pos 0
#define	eagle_reg_top_gpioh2_i_len 1
#define	eagle_reg_top_gpioh2_i_lsb 0
#define xd_p_eagle_reg_top_gpioh2_o	(*(volatile byte xdata *) 0xD8B7)
#define    p_eagle_reg_top_gpioh2_o	0xD8B7 
#define	eagle_reg_top_gpioh2_o_pos 0
#define	eagle_reg_top_gpioh2_o_len 1
#define	eagle_reg_top_gpioh2_o_lsb 0
#define xd_p_eagle_reg_top_gpioh2_en	(*(volatile byte xdata *) 0xD8B8)
#define    p_eagle_reg_top_gpioh2_en	0xD8B8 
#define	eagle_reg_top_gpioh2_en_pos 0
#define	eagle_reg_top_gpioh2_en_len 1
#define	eagle_reg_top_gpioh2_en_lsb 0
#define xd_p_eagle_reg_top_gpioh2_on	(*(volatile byte xdata *) 0xD8B9)
#define    p_eagle_reg_top_gpioh2_on	0xD8B9 
#define	eagle_reg_top_gpioh2_on_pos 0
#define	eagle_reg_top_gpioh2_on_len 1
#define	eagle_reg_top_gpioh2_on_lsb 0
#define xd_r_eagle_reg_top_gpioh5_i	(*(volatile byte xdata *) 0xD8BA)
#define    r_eagle_reg_top_gpioh5_i	0xD8BA 
#define	eagle_reg_top_gpioh5_i_pos 0
#define	eagle_reg_top_gpioh5_i_len 1
#define	eagle_reg_top_gpioh5_i_lsb 0
#define xd_p_eagle_reg_top_gpioh5_o	(*(volatile byte xdata *) 0xD8BB)
#define    p_eagle_reg_top_gpioh5_o	0xD8BB 
#define	eagle_reg_top_gpioh5_o_pos 0
#define	eagle_reg_top_gpioh5_o_len 1
#define	eagle_reg_top_gpioh5_o_lsb 0
#define xd_p_eagle_reg_top_gpioh5_en	(*(volatile byte xdata *) 0xD8BC)
#define    p_eagle_reg_top_gpioh5_en	0xD8BC 
#define	eagle_reg_top_gpioh5_en_pos 0
#define	eagle_reg_top_gpioh5_en_len 1
#define	eagle_reg_top_gpioh5_en_lsb 0
#define xd_p_eagle_reg_top_gpioh5_on	(*(volatile byte xdata *) 0xD8BD)
#define    p_eagle_reg_top_gpioh5_on	0xD8BD 
#define	eagle_reg_top_gpioh5_on_pos 0
#define	eagle_reg_top_gpioh5_on_len 1
#define	eagle_reg_top_gpioh5_on_lsb 0
#define xd_r_eagle_reg_top_gpioh4_i	(*(volatile byte xdata *) 0xD8BE)
#define    r_eagle_reg_top_gpioh4_i	0xD8BE 
#define	eagle_reg_top_gpioh4_i_pos 0
#define	eagle_reg_top_gpioh4_i_len 1
#define	eagle_reg_top_gpioh4_i_lsb 0
#define xd_p_eagle_reg_top_gpioh4_o	(*(volatile byte xdata *) 0xD8BF)
#define    p_eagle_reg_top_gpioh4_o	0xD8BF 
#define	eagle_reg_top_gpioh4_o_pos 0
#define	eagle_reg_top_gpioh4_o_len 1
#define	eagle_reg_top_gpioh4_o_lsb 0
#define xd_p_eagle_reg_top_gpioh4_en	(*(volatile byte xdata *) 0xD8C0)
#define    p_eagle_reg_top_gpioh4_en	0xD8C0 
#define	eagle_reg_top_gpioh4_en_pos 0
#define	eagle_reg_top_gpioh4_en_len 1
#define	eagle_reg_top_gpioh4_en_lsb 0
#define xd_p_eagle_reg_top_gpioh4_on	(*(volatile byte xdata *) 0xD8C1)
#define    p_eagle_reg_top_gpioh4_on	0xD8C1 
#define	eagle_reg_top_gpioh4_on_pos 0
#define	eagle_reg_top_gpioh4_on_len 1
#define	eagle_reg_top_gpioh4_on_lsb 0
#define xd_r_eagle_reg_top_gpioh7_i	(*(volatile byte xdata *) 0xD8C2)
#define    r_eagle_reg_top_gpioh7_i	0xD8C2 
#define	eagle_reg_top_gpioh7_i_pos 0
#define	eagle_reg_top_gpioh7_i_len 1
#define	eagle_reg_top_gpioh7_i_lsb 0
#define xd_p_eagle_reg_top_gpioh7_o	(*(volatile byte xdata *) 0xD8C3)
#define    p_eagle_reg_top_gpioh7_o	0xD8C3 
#define	eagle_reg_top_gpioh7_o_pos 0
#define	eagle_reg_top_gpioh7_o_len 1
#define	eagle_reg_top_gpioh7_o_lsb 0
#define xd_p_eagle_reg_top_gpioh7_en	(*(volatile byte xdata *) 0xD8C4)
#define    p_eagle_reg_top_gpioh7_en	0xD8C4 
#define	eagle_reg_top_gpioh7_en_pos 0
#define	eagle_reg_top_gpioh7_en_len 1
#define	eagle_reg_top_gpioh7_en_lsb 0
#define xd_p_eagle_reg_top_gpioh7_on	(*(volatile byte xdata *) 0xD8C5)
#define    p_eagle_reg_top_gpioh7_on	0xD8C5 
#define	eagle_reg_top_gpioh7_on_pos 0
#define	eagle_reg_top_gpioh7_on_len 1
#define	eagle_reg_top_gpioh7_on_lsb 0
#define xd_r_eagle_reg_top_gpioh6_i	(*(volatile byte xdata *) 0xD8C6)
#define    r_eagle_reg_top_gpioh6_i	0xD8C6 
#define	eagle_reg_top_gpioh6_i_pos 0
#define	eagle_reg_top_gpioh6_i_len 1
#define	eagle_reg_top_gpioh6_i_lsb 0
#define xd_p_eagle_reg_top_gpioh6_o	(*(volatile byte xdata *) 0xD8C7)
#define    p_eagle_reg_top_gpioh6_o	0xD8C7 
#define	eagle_reg_top_gpioh6_o_pos 0
#define	eagle_reg_top_gpioh6_o_len 1
#define	eagle_reg_top_gpioh6_o_lsb 0
#define xd_p_eagle_reg_top_gpioh6_en	(*(volatile byte xdata *) 0xD8C8)
#define    p_eagle_reg_top_gpioh6_en	0xD8C8 
#define	eagle_reg_top_gpioh6_en_pos 0
#define	eagle_reg_top_gpioh6_en_len 1
#define	eagle_reg_top_gpioh6_en_lsb 0
#define xd_p_eagle_reg_top_gpioh6_on	(*(volatile byte xdata *) 0xD8C9)
#define    p_eagle_reg_top_gpioh6_on	0xD8C9 
#define	eagle_reg_top_gpioh6_on_pos 0
#define	eagle_reg_top_gpioh6_on_len 1
#define	eagle_reg_top_gpioh6_on_lsb 0
#define xd_r_eagle_reg_top_gpioh8_i	(*(volatile byte xdata *) 0xD8CE)
#define    r_eagle_reg_top_gpioh8_i	0xD8CE 
#define	eagle_reg_top_gpioh8_i_pos 0
#define	eagle_reg_top_gpioh8_i_len 1
#define	eagle_reg_top_gpioh8_i_lsb 0
#define xd_p_eagle_reg_top_gpioh8_o	(*(volatile byte xdata *) 0xD8CF)
#define    p_eagle_reg_top_gpioh8_o	0xD8CF 
#define	eagle_reg_top_gpioh8_o_pos 0
#define	eagle_reg_top_gpioh8_o_len 1
#define	eagle_reg_top_gpioh8_o_lsb 0
#define xd_p_eagle_reg_top_gpioh8_en	(*(volatile byte xdata *) 0xD8D0)
#define    p_eagle_reg_top_gpioh8_en	0xD8D0 
#define	eagle_reg_top_gpioh8_en_pos 0
#define	eagle_reg_top_gpioh8_en_len 1
#define	eagle_reg_top_gpioh8_en_lsb 0
#define xd_p_eagle_reg_top_gpioh8_on	(*(volatile byte xdata *) 0xD8D1)
#define    p_eagle_reg_top_gpioh8_on	0xD8D1 
#define	eagle_reg_top_gpioh8_on_pos 0
#define	eagle_reg_top_gpioh8_on_len 1
#define	eagle_reg_top_gpioh8_on_lsb 0
#define xd_p_eagle_reg_top_lock3_out	(*(volatile byte xdata *) 0xD8FD)
#define    p_eagle_reg_top_lock3_out	0xD8FD 
#define	eagle_reg_top_lock3_out_pos 0
#define	eagle_reg_top_lock3_out_len 1
#define	eagle_reg_top_lock3_out_lsb 0
#define xd_p_eagle_reg_top_hostb_mpeg_par_mode	(*(volatile byte xdata *) 0xD91B)
#define    p_eagle_reg_top_hostb_mpeg_par_mode	0xD91B 
#define	eagle_reg_top_hostb_mpeg_par_mode_pos 0
#define	eagle_reg_top_hostb_mpeg_par_mode_len 1
#define	eagle_reg_top_hostb_mpeg_par_mode_lsb 0
#define xd_p_eagle_reg_top_hostb_mpeg_ser_mode	(*(volatile byte xdata *) 0xD91C)
#define    p_eagle_reg_top_hostb_mpeg_ser_mode	0xD91C 
#define	eagle_reg_top_hostb_mpeg_ser_mode_pos 0
#define	eagle_reg_top_hostb_mpeg_ser_mode_len 1
#define	eagle_reg_top_hostb_mpeg_ser_mode_lsb 0
#define xd_p_eagle_reg_top_hostb_mpeg_ser_do7	(*(volatile byte xdata *) 0xD91D)
#define    p_eagle_reg_top_hostb_mpeg_ser_do7	0xD91D 
#define	eagle_reg_top_hostb_mpeg_ser_do7_pos 0
#define	eagle_reg_top_hostb_mpeg_ser_do7_len 1
#define	eagle_reg_top_hostb_mpeg_ser_do7_lsb 0
#define xd_p_eagle_reg_top_host_reverse	(*(volatile byte xdata *) 0xD920)
#define    p_eagle_reg_top_host_reverse	0xD920 
#define	eagle_reg_top_host_reverse_pos 0
#define	eagle_reg_top_host_reverse_len 1
#define	eagle_reg_top_host_reverse_lsb 0

#define xd_p_eagle_reg_one_cycle_counter_tuner	(*(volatile byte xdata *) 0xF103)
#define    p_eagle_reg_one_cycle_counter_tuner	0xF103 
#define	eagle_reg_one_cycle_counter_tuner_pos 0
#define	eagle_reg_one_cycle_counter_tuner_len 8
#define	eagle_reg_one_cycle_counter_tuner_lsb 0
#define xd_r_link_ofsm_dvbt_int	(*(volatile byte xdata *) 0xF403)
#define    r_link_ofsm_dvbt_int	0xF403 
#define	link_ofsm_dvbt_int_pos 2
#define	link_ofsm_dvbt_int_len 1
#define	link_ofsm_dvbt_int_lsb 0
#define xd_p_eagle_reg_dvbt_intsts	(*(volatile byte xdata *) 0xF404)
#define    p_eagle_reg_dvbt_intsts	0xF404 
#define	eagle_reg_dvbt_intsts_pos 2
#define	eagle_reg_dvbt_intsts_len 1
#define	eagle_reg_dvbt_intsts_lsb 0
#define xd_p_eagle_reg_dvbt_en	(*(volatile byte xdata *) 0xF41A)
#define    p_eagle_reg_dvbt_en	0xF41A 
#define	eagle_reg_dvbt_en_pos 0
#define	eagle_reg_dvbt_en_len 1
#define	eagle_reg_dvbt_en_lsb 0
#define xd_p_eagle_reg_dvbt_bufsize	(*(volatile byte xdata *) 0xF41A)
#define    p_eagle_reg_dvbt_bufsize	0xF41A 
#define	eagle_reg_dvbt_bufsize_pos 1
#define	eagle_reg_dvbt_bufsize_len 1
#define	eagle_reg_dvbt_bufsize_lsb 0
#define xd_p_eagle_reg_dvbt_path	(*(volatile byte xdata *) 0xF41A)
#define    p_eagle_reg_dvbt_path	0xF41A 
#define	eagle_reg_dvbt_path_pos 2
#define	eagle_reg_dvbt_path_len 1
#define	eagle_reg_dvbt_path_lsb 0
#define xd_p_eagle_reg_dvbt_inten	(*(volatile byte xdata *) 0xF41F)
#define    p_eagle_reg_dvbt_inten	0xF41F 
#define	eagle_reg_dvbt_inten_pos 2
#define	eagle_reg_dvbt_inten_len 1
#define	eagle_reg_dvbt_inten_lsb 0
#define xd_r_link_ofsm_ip_valid	(*(volatile byte xdata *) 0xF448)
#define    r_link_ofsm_ip_valid	0xF448 
#define	link_ofsm_ip_valid_pos 7
#define	link_ofsm_ip_valid_len 1
#define	link_ofsm_ip_valid_lsb 0
// usb_biu_reg.h 8-1-2011
// gen_biu Ver 1.0 generated by cphsu 
#define xd_p_eagle_reg_usb_cfg_speed	(*(volatile byte xdata *) 0xDD00)
#define    p_eagle_reg_usb_cfg_speed	0xDD00 
#define	eagle_reg_usb_cfg_speed_pos 0
#define	eagle_reg_usb_cfg_speed_len 1
#define	eagle_reg_usb_cfg_speed_lsb 0
#define xd_p_eagle_reg_usb_cfg_utmi16	(*(volatile byte xdata *) 0xDD00)
#define    p_eagle_reg_usb_cfg_utmi16	0xDD00 
#define	eagle_reg_usb_cfg_utmi16_pos 1
#define	eagle_reg_usb_cfg_utmi16_len 1
#define	eagle_reg_usb_cfg_utmi16_lsb 0
#define xd_p_eagle_reg_usb_cfg_test	(*(volatile byte xdata *) 0xDD00)
#define    p_eagle_reg_usb_cfg_test	0xDD00 
#define	eagle_reg_usb_cfg_test_pos 3
#define	eagle_reg_usb_cfg_test_len 3
#define	eagle_reg_usb_cfg_test_lsb 0
#define xd_p_eagle_reg_usb_port_sim_reset	(*(volatile byte xdata *) 0xDD00)
#define    p_eagle_reg_usb_port_sim_reset	0xDD00 
#define	eagle_reg_usb_port_sim_reset_pos 6
#define	eagle_reg_usb_port_sim_reset_len 1
#define	eagle_reg_usb_port_sim_reset_lsb 0
#define xd_p_eagle_reg_usb_port_run	(*(volatile byte xdata *) 0xDD00)
#define    p_eagle_reg_usb_port_run	0xDD00 
#define	eagle_reg_usb_port_run_pos 7
#define	eagle_reg_usb_port_run_len 1
#define	eagle_reg_usb_port_run_lsb 0
#define xd_r_usb_line_state_0	(*(volatile byte xdata *) 0xDD01)
#define    r_usb_line_state_0	0xDD01 
#define	usb_line_state_0_pos 0
#define	usb_line_state_0_len 1
#define	usb_line_state_0_lsb 0
#define xd_r_usb_line_state_1	(*(volatile byte xdata *) 0xDD01)
#define    r_usb_line_state_1	0xDD01 
#define	usb_line_state_1_pos 1
#define	usb_line_state_1_len 1
#define	usb_line_state_1_lsb 0
#define xd_r_eagle_reg_usb_status_speed	(*(volatile byte xdata *) 0xDD01)
#define    r_eagle_reg_usb_status_speed	0xDD01 
#define	eagle_reg_usb_status_speed_pos 2
#define	eagle_reg_usb_status_speed_len 1
#define	eagle_reg_usb_status_speed_lsb 0
#define xd_r_eagle_reg_usb_status_connect	(*(volatile byte xdata *) 0xDD01)
#define    r_eagle_reg_usb_status_connect	0xDD01 
#define	eagle_reg_usb_status_connect_pos 3
#define	eagle_reg_usb_status_connect_len 1
#define	eagle_reg_usb_status_connect_lsb 0
#define xd_r_eagle_reg_usb_rx_buf	(*(volatile byte xdata *) 0xDD01)
#define    r_eagle_reg_usb_rx_buf	0xDD01 
#define	eagle_reg_usb_rx_buf_pos 4
#define	eagle_reg_usb_rx_buf_len 1
#define	eagle_reg_usb_rx_buf_lsb 0
#define xd_r_eagle_reg_usb_port_reset	(*(volatile byte xdata *) 0xDD01)
#define    r_eagle_reg_usb_port_reset	0xDD01 
#define	eagle_reg_usb_port_reset_pos 5
#define	eagle_reg_usb_port_reset_len 1
#define	eagle_reg_usb_port_reset_lsb 0
#define xd_r_eagle_reg_usb_port_suspend	(*(volatile byte xdata *) 0xDD01)
#define    r_eagle_reg_usb_port_suspend	0xDD01 
#define	eagle_reg_usb_port_suspend_pos 6
#define	eagle_reg_usb_port_suspend_len 1
#define	eagle_reg_usb_port_suspend_lsb 0
#define xd_r_eagle_reg_usb_rx_buf1	(*(volatile byte xdata *) 0xDD01)
#define    r_eagle_reg_usb_rx_buf1	0xDD01 
#define	eagle_reg_usb_rx_buf1_pos 7
#define	eagle_reg_usb_rx_buf1_len 1
#define	eagle_reg_usb_rx_buf1_lsb 0
#define xd_p_eagle_reg_ep1_tx_type	(*(volatile byte xdata *) 0xDD07)
#define    p_eagle_reg_ep1_tx_type	0xDD07 
#define	eagle_reg_ep1_tx_type_pos 2
#define	eagle_reg_ep1_tx_type_len 1
#define	eagle_reg_ep1_tx_type_lsb 0
#define xd_p_eagle_reg_ep2_rx_type	(*(volatile byte xdata *) 0xDD07)
#define    p_eagle_reg_ep2_rx_type	0xDD07 
#define	eagle_reg_ep2_rx_type_pos 3
#define	eagle_reg_ep2_rx_type_len 1
#define	eagle_reg_ep2_rx_type_lsb 0
#define xd_p_eagle_reg_ep3_tx_type	(*(volatile byte xdata *) 0xDD07)
#define    p_eagle_reg_ep3_tx_type	0xDD07 
#define	eagle_reg_ep3_tx_type_pos 4
#define	eagle_reg_ep3_tx_type_len 1
#define	eagle_reg_ep3_tx_type_lsb 0
#define xd_p_eagle_reg_ep5_tx_type	(*(volatile byte xdata *) 0xDD07)
#define    p_eagle_reg_ep5_tx_type	0xDD07 
#define	eagle_reg_ep5_tx_type_pos 6
#define	eagle_reg_ep5_tx_type_len 1
#define	eagle_reg_ep5_tx_type_lsb 0
#define xd_p_eagle_reg_ep6_rx_type	(*(volatile byte xdata *) 0xDD07)
#define    p_eagle_reg_ep6_rx_type	0xDD07 
#define	eagle_reg_ep6_rx_type_pos 7
#define	eagle_reg_ep6_rx_type_len 1
#define	eagle_reg_ep6_rx_type_lsb 0
#define xd_p_eagle_reg_ep0_max_pkt	(*(volatile byte xdata *) 0xDD08)
#define    p_eagle_reg_ep0_max_pkt	0xDD08 
#define	eagle_reg_ep0_max_pkt_pos 0
#define	eagle_reg_ep0_max_pkt_len 8
#define	eagle_reg_ep0_max_pkt_lsb 0
#define xd_p_eagle_reg_ep2_max_pkt	(*(volatile byte xdata *) 0xDD0A)
#define    p_eagle_reg_ep2_max_pkt	0xDD0A 
#define	eagle_reg_ep2_max_pkt_pos 0
#define	eagle_reg_ep2_max_pkt_len 8
#define	eagle_reg_ep2_max_pkt_lsb 0
#define xd_p_eagle_reg_ep5_max_pkt	(*(volatile byte xdata *) 0xDD0D)
#define    p_eagle_reg_ep5_max_pkt	0xDD0D 
#define	eagle_reg_ep5_max_pkt_pos 0
#define	eagle_reg_ep5_max_pkt_len 8
#define	eagle_reg_ep5_max_pkt_lsb 0
#define xd_p_eagle_reg_ep6_max_pkt	(*(volatile byte xdata *) 0xDD0E)
#define    p_eagle_reg_ep6_max_pkt	0xDD0E 
#define	eagle_reg_ep6_max_pkt_pos 0
#define	eagle_reg_ep6_max_pkt_len 8
#define	eagle_reg_ep6_max_pkt_lsb 0
#define xd_p_eagle_reg_usb_addr	(*(volatile byte xdata *) 0xDD10)
#define    p_eagle_reg_usb_addr	0xDD10 
#define	eagle_reg_usb_addr_pos 0
#define	eagle_reg_usb_addr_len 7
#define	eagle_reg_usb_addr_lsb 0
#define xd_p_eagle_reg_usb_addr_now	(*(volatile byte xdata *) 0xDD10)
#define    p_eagle_reg_usb_addr_now	0xDD10 
#define	eagle_reg_usb_addr_now_pos 7
#define	eagle_reg_usb_addr_now_len 1
#define	eagle_reg_usb_addr_now_lsb 0
#define xd_p_eagle_reg_ep0_tx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep0_tx_en	0xDD11 
#define	eagle_reg_ep0_tx_en_pos 0
#define	eagle_reg_ep0_tx_en_len 1
#define	eagle_reg_ep0_tx_en_lsb 0
#define xd_p_eagle_reg_ep0_rx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep0_rx_en	0xDD11 
#define	eagle_reg_ep0_rx_en_pos 1
#define	eagle_reg_ep0_rx_en_len 1
#define	eagle_reg_ep0_rx_en_lsb 0
#define xd_p_eagle_reg_ep1_tx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep1_tx_en	0xDD11 
#define	eagle_reg_ep1_tx_en_pos 2
#define	eagle_reg_ep1_tx_en_len 1
#define	eagle_reg_ep1_tx_en_lsb 0
#define xd_p_eagle_reg_ep2_rx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep2_rx_en	0xDD11 
#define	eagle_reg_ep2_rx_en_pos 3
#define	eagle_reg_ep2_rx_en_len 1
#define	eagle_reg_ep2_rx_en_lsb 0
#define xd_p_eagle_reg_ep3_tx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep3_tx_en	0xDD11 
#define	eagle_reg_ep3_tx_en_pos 4
#define	eagle_reg_ep3_tx_en_len 1
#define	eagle_reg_ep3_tx_en_lsb 0
#define xd_p_eagle_reg_ep5_tx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep5_tx_en	0xDD11 
#define	eagle_reg_ep5_tx_en_pos 6
#define	eagle_reg_ep5_tx_en_len 1
#define	eagle_reg_ep5_tx_en_lsb 0
#define xd_p_eagle_reg_ep6_rx_en	(*(volatile byte xdata *) 0xDD11)
#define    p_eagle_reg_ep6_rx_en	0xDD11 
#define	eagle_reg_ep6_rx_en_pos 7
#define	eagle_reg_ep6_rx_en_len 1
#define	eagle_reg_ep6_rx_en_lsb 0
#define xd_p_eagle_reg_ep0_tx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep0_tx_stall	0xDD12 
#define	eagle_reg_ep0_tx_stall_pos 0
#define	eagle_reg_ep0_tx_stall_len 1
#define	eagle_reg_ep0_tx_stall_lsb 0
#define xd_p_eagle_reg_ep0_rx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep0_rx_stall	0xDD12 
#define	eagle_reg_ep0_rx_stall_pos 1
#define	eagle_reg_ep0_rx_stall_len 1
#define	eagle_reg_ep0_rx_stall_lsb 0
#define xd_p_eagle_reg_ep1_tx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep1_tx_stall	0xDD12 
#define	eagle_reg_ep1_tx_stall_pos 2
#define	eagle_reg_ep1_tx_stall_len 1
#define	eagle_reg_ep1_tx_stall_lsb 0
#define xd_p_eagle_reg_ep2_rx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep2_rx_stall	0xDD12 
#define	eagle_reg_ep2_rx_stall_pos 3
#define	eagle_reg_ep2_rx_stall_len 1
#define	eagle_reg_ep2_rx_stall_lsb 0
#define xd_p_eagle_reg_ep3_tx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep3_tx_stall	0xDD12 
#define	eagle_reg_ep3_tx_stall_pos 4
#define	eagle_reg_ep3_tx_stall_len 1
#define	eagle_reg_ep3_tx_stall_lsb 0
#define xd_p_eagle_reg_ep5_tx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep5_tx_stall	0xDD12 
#define	eagle_reg_ep5_tx_stall_pos 6
#define	eagle_reg_ep5_tx_stall_len 1
#define	eagle_reg_ep5_tx_stall_lsb 0
#define xd_p_eagle_reg_ep6_rx_stall	(*(volatile byte xdata *) 0xDD12)
#define    p_eagle_reg_ep6_rx_stall	0xDD12 
#define	eagle_reg_ep6_rx_stall_pos 7
#define	eagle_reg_ep6_rx_stall_len 1
#define	eagle_reg_ep6_rx_stall_lsb 0
#define xd_p_eagle_reg_ep0_tx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep0_tx_nak	0xDD13 
#define	eagle_reg_ep0_tx_nak_pos 0
#define	eagle_reg_ep0_tx_nak_len 1
#define	eagle_reg_ep0_tx_nak_lsb 0
#define xd_p_eagle_reg_ep0_rx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep0_rx_nak	0xDD13 
#define	eagle_reg_ep0_rx_nak_pos 1
#define	eagle_reg_ep0_rx_nak_len 1
#define	eagle_reg_ep0_rx_nak_lsb 0
#define xd_p_eagle_reg_ep1_tx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep1_tx_nak	0xDD13 
#define	eagle_reg_ep1_tx_nak_pos 2
#define	eagle_reg_ep1_tx_nak_len 1
#define	eagle_reg_ep1_tx_nak_lsb 0
#define xd_p_eagle_reg_ep2_rx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep2_rx_nak	0xDD13 
#define	eagle_reg_ep2_rx_nak_pos 3
#define	eagle_reg_ep2_rx_nak_len 1
#define	eagle_reg_ep2_rx_nak_lsb 0
#define xd_p_eagle_reg_ep3_tx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep3_tx_nak	0xDD13 
#define	eagle_reg_ep3_tx_nak_pos 4
#define	eagle_reg_ep3_tx_nak_len 1
#define	eagle_reg_ep3_tx_nak_lsb 0
#define xd_p_eagle_reg_ep5_tx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep5_tx_nak	0xDD13 
#define	eagle_reg_ep5_tx_nak_pos 6
#define	eagle_reg_ep5_tx_nak_len 1
#define	eagle_reg_ep5_tx_nak_lsb 0
#define xd_p_eagle_reg_ep6_rx_nak	(*(volatile byte xdata *) 0xDD13)
#define    p_eagle_reg_ep6_rx_nak	0xDD13 
#define	eagle_reg_ep6_rx_nak_pos 7
#define	eagle_reg_ep6_rx_nak_len 1
#define	eagle_reg_ep6_rx_nak_lsb 0
#define xd_p_eagle_reg_ep0_tx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep0_tx_nak_int_en	0xDD14 
#define	eagle_reg_ep0_tx_nak_int_en_pos 0
#define	eagle_reg_ep0_tx_nak_int_en_len 1
#define	eagle_reg_ep0_tx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep0_rx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep0_rx_nak_int_en	0xDD14 
#define	eagle_reg_ep0_rx_nak_int_en_pos 1
#define	eagle_reg_ep0_rx_nak_int_en_len 1
#define	eagle_reg_ep0_rx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep1_tx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep1_tx_nak_int_en	0xDD14 
#define	eagle_reg_ep1_tx_nak_int_en_pos 2
#define	eagle_reg_ep1_tx_nak_int_en_len 1
#define	eagle_reg_ep1_tx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep2_rx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep2_rx_nak_int_en	0xDD14 
#define	eagle_reg_ep2_rx_nak_int_en_pos 3
#define	eagle_reg_ep2_rx_nak_int_en_len 1
#define	eagle_reg_ep2_rx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep3_tx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep3_tx_nak_int_en	0xDD14 
#define	eagle_reg_ep3_tx_nak_int_en_pos 4
#define	eagle_reg_ep3_tx_nak_int_en_len 1
#define	eagle_reg_ep3_tx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep5_tx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep5_tx_nak_int_en	0xDD14 
#define	eagle_reg_ep5_tx_nak_int_en_pos 6
#define	eagle_reg_ep5_tx_nak_int_en_len 1
#define	eagle_reg_ep5_tx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep6_rx_nak_int_en	(*(volatile byte xdata *) 0xDD14)
#define    p_eagle_reg_ep6_rx_nak_int_en	0xDD14 
#define	eagle_reg_ep6_rx_nak_int_en_pos 7
#define	eagle_reg_ep6_rx_nak_int_en_len 1
#define	eagle_reg_ep6_rx_nak_int_en_lsb 0
#define xd_p_eagle_reg_ep0_tx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep0_tx_done_int_en	0xDD15 
#define	eagle_reg_ep0_tx_done_int_en_pos 0
#define	eagle_reg_ep0_tx_done_int_en_len 1
#define	eagle_reg_ep0_tx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep0_rx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep0_rx_done_int_en	0xDD15 
#define	eagle_reg_ep0_rx_done_int_en_pos 1
#define	eagle_reg_ep0_rx_done_int_en_len 1
#define	eagle_reg_ep0_rx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep1_tx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep1_tx_done_int_en	0xDD15 
#define	eagle_reg_ep1_tx_done_int_en_pos 2
#define	eagle_reg_ep1_tx_done_int_en_len 1
#define	eagle_reg_ep1_tx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep2_rx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep2_rx_done_int_en	0xDD15 
#define	eagle_reg_ep2_rx_done_int_en_pos 3
#define	eagle_reg_ep2_rx_done_int_en_len 1
#define	eagle_reg_ep2_rx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep3_tx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep3_tx_done_int_en	0xDD15 
#define	eagle_reg_ep3_tx_done_int_en_pos 4
#define	eagle_reg_ep3_tx_done_int_en_len 1
#define	eagle_reg_ep3_tx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep5_tx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep5_tx_done_int_en	0xDD15 
#define	eagle_reg_ep5_tx_done_int_en_pos 6
#define	eagle_reg_ep5_tx_done_int_en_len 1
#define	eagle_reg_ep5_tx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep6_rx_done_int_en	(*(volatile byte xdata *) 0xDD15)
#define    p_eagle_reg_ep6_rx_done_int_en	0xDD15 
#define	eagle_reg_ep6_rx_done_int_en_pos 7
#define	eagle_reg_ep6_rx_done_int_en_len 1
#define	eagle_reg_ep6_rx_done_int_en_lsb 0
#define xd_p_eagle_reg_ep0_tx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep0_tx_fail_int_en	0xDD16 
#define	eagle_reg_ep0_tx_fail_int_en_pos 0
#define	eagle_reg_ep0_tx_fail_int_en_len 1
#define	eagle_reg_ep0_tx_fail_int_en_lsb 0
#define xd_p_eagle_reg_ep0_rx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep0_rx_fail_int_en	0xDD16 
#define	eagle_reg_ep0_rx_fail_int_en_pos 1
#define	eagle_reg_ep0_rx_fail_int_en_len 1
#define	eagle_reg_ep0_rx_fail_int_en_lsb 0
#define xd_p_eagle_reg_ep1_tx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep1_tx_fail_int_en	0xDD16 
#define	eagle_reg_ep1_tx_fail_int_en_pos 2
#define	eagle_reg_ep1_tx_fail_int_en_len 1
#define	eagle_reg_ep1_tx_fail_int_en_lsb 0
#define xd_p_eagle_reg_ep2_rx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep2_rx_fail_int_en	0xDD16 
#define	eagle_reg_ep2_rx_fail_int_en_pos 3
#define	eagle_reg_ep2_rx_fail_int_en_len 1
#define	eagle_reg_ep2_rx_fail_int_en_lsb 0
#define xd_p_eagle_reg_ep3_tx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep3_tx_fail_int_en	0xDD16 
#define	eagle_reg_ep3_tx_fail_int_en_pos 4
#define	eagle_reg_ep3_tx_fail_int_en_len 1
#define	eagle_reg_ep3_tx_fail_int_en_lsb 0
#define xd_p_eagle_reg_ep5_tx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep5_tx_fail_int_en	0xDD16 
#define	eagle_reg_ep5_tx_fail_int_en_pos 6
#define	eagle_reg_ep5_tx_fail_int_en_len 1
#define	eagle_reg_ep5_tx_fail_int_en_lsb 0
#define xd_p_eagle_reg_ep6_rx_fail_int_en	(*(volatile byte xdata *) 0xDD16)
#define    p_eagle_reg_ep6_rx_fail_int_en	0xDD16 
#define	eagle_reg_ep6_rx_fail_int_en_pos 7
#define	eagle_reg_ep6_rx_fail_int_en_len 1
#define	eagle_reg_ep6_rx_fail_int_en_lsb 0
#define xd_p_eagle_reg_suspend_int_en	(*(volatile byte xdata *) 0xDD17)
#define    p_eagle_reg_suspend_int_en	0xDD17 
#define	eagle_reg_suspend_int_en_pos 0
#define	eagle_reg_suspend_int_en_len 1
#define	eagle_reg_suspend_int_en_lsb 0
#define xd_p_eagle_reg_bus_reset_int_en	(*(volatile byte xdata *) 0xDD17)
#define    p_eagle_reg_bus_reset_int_en	0xDD17 
#define	eagle_reg_bus_reset_int_en_pos 1
#define	eagle_reg_bus_reset_int_en_len 1
#define	eagle_reg_bus_reset_int_en_lsb 0
#define xd_p_eagle_reg_ep0_setup_int_en	(*(volatile byte xdata *) 0xDD17)
#define    p_eagle_reg_ep0_setup_int_en	0xDD17 
#define	eagle_reg_ep0_setup_int_en_pos 2
#define	eagle_reg_ep0_setup_int_en_len 1
#define	eagle_reg_ep0_setup_int_en_lsb 0
#define xd_p_eagle_reg_ep0_tx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep0_tx_nak_int	0xDD18 
#define	eagle_reg_ep0_tx_nak_int_pos 0
#define	eagle_reg_ep0_tx_nak_int_len 1
#define	eagle_reg_ep0_tx_nak_int_lsb 0
#define xd_p_eagle_reg_ep0_rx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep0_rx_nak_int	0xDD18 
#define	eagle_reg_ep0_rx_nak_int_pos 1
#define	eagle_reg_ep0_rx_nak_int_len 1
#define	eagle_reg_ep0_rx_nak_int_lsb 0
#define xd_p_eagle_reg_ep1_tx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep1_tx_nak_int	0xDD18 
#define	eagle_reg_ep1_tx_nak_int_pos 2
#define	eagle_reg_ep1_tx_nak_int_len 1
#define	eagle_reg_ep1_tx_nak_int_lsb 0
#define xd_p_eagle_reg_ep2_rx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep2_rx_nak_int	0xDD18 
#define	eagle_reg_ep2_rx_nak_int_pos 3
#define	eagle_reg_ep2_rx_nak_int_len 1
#define	eagle_reg_ep2_rx_nak_int_lsb 0
#define xd_p_eagle_reg_ep3_tx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep3_tx_nak_int	0xDD18 
#define	eagle_reg_ep3_tx_nak_int_pos 4
#define	eagle_reg_ep3_tx_nak_int_len 1
#define	eagle_reg_ep3_tx_nak_int_lsb 0
#define xd_p_eagle_reg_ep5_tx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep5_tx_nak_int	0xDD18 
#define	eagle_reg_ep5_tx_nak_int_pos 6
#define	eagle_reg_ep5_tx_nak_int_len 1
#define	eagle_reg_ep5_tx_nak_int_lsb 0
#define xd_p_eagle_reg_ep6_rx_nak_int	(*(volatile byte xdata *) 0xDD18)
#define    p_eagle_reg_ep6_rx_nak_int	0xDD18 
#define	eagle_reg_ep6_rx_nak_int_pos 7
#define	eagle_reg_ep6_rx_nak_int_len 1
#define	eagle_reg_ep6_rx_nak_int_lsb 0
#define xd_p_eagle_reg_ep0_tx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep0_tx_done_int	0xDD19 
#define	eagle_reg_ep0_tx_done_int_pos 0
#define	eagle_reg_ep0_tx_done_int_len 1
#define	eagle_reg_ep0_tx_done_int_lsb 0
#define xd_p_eagle_reg_ep0_rx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep0_rx_done_int	0xDD19 
#define	eagle_reg_ep0_rx_done_int_pos 1
#define	eagle_reg_ep0_rx_done_int_len 1
#define	eagle_reg_ep0_rx_done_int_lsb 0
#define xd_p_eagle_reg_ep1_tx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep1_tx_done_int	0xDD19 
#define	eagle_reg_ep1_tx_done_int_pos 2
#define	eagle_reg_ep1_tx_done_int_len 1
#define	eagle_reg_ep1_tx_done_int_lsb 0
#define xd_p_eagle_reg_ep2_rx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep2_rx_done_int	0xDD19 
#define	eagle_reg_ep2_rx_done_int_pos 3
#define	eagle_reg_ep2_rx_done_int_len 1
#define	eagle_reg_ep2_rx_done_int_lsb 0
#define xd_p_eagle_reg_ep3_tx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep3_tx_done_int	0xDD19 
#define	eagle_reg_ep3_tx_done_int_pos 4
#define	eagle_reg_ep3_tx_done_int_len 1
#define	eagle_reg_ep3_tx_done_int_lsb 0
#define xd_p_eagle_reg_ep5_tx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep5_tx_done_int	0xDD19 
#define	eagle_reg_ep5_tx_done_int_pos 6
#define	eagle_reg_ep5_tx_done_int_len 1
#define	eagle_reg_ep5_tx_done_int_lsb 0
#define xd_p_eagle_reg_ep6_rx_done_int	(*(volatile byte xdata *) 0xDD19)
#define    p_eagle_reg_ep6_rx_done_int	0xDD19 
#define	eagle_reg_ep6_rx_done_int_pos 7
#define	eagle_reg_ep6_rx_done_int_len 1
#define	eagle_reg_ep6_rx_done_int_lsb 0
#define xd_p_eagle_reg_ep0_tx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep0_tx_fail_int	0xDD1A 
#define	eagle_reg_ep0_tx_fail_int_pos 0
#define	eagle_reg_ep0_tx_fail_int_len 1
#define	eagle_reg_ep0_tx_fail_int_lsb 0
#define xd_p_eagle_reg_ep0_rx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep0_rx_fail_int	0xDD1A 
#define	eagle_reg_ep0_rx_fail_int_pos 1
#define	eagle_reg_ep0_rx_fail_int_len 1
#define	eagle_reg_ep0_rx_fail_int_lsb 0
#define xd_p_eagle_reg_ep1_tx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep1_tx_fail_int	0xDD1A 
#define	eagle_reg_ep1_tx_fail_int_pos 2
#define	eagle_reg_ep1_tx_fail_int_len 1
#define	eagle_reg_ep1_tx_fail_int_lsb 0
#define xd_p_eagle_reg_ep2_rx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep2_rx_fail_int	0xDD1A 
#define	eagle_reg_ep2_rx_fail_int_pos 3
#define	eagle_reg_ep2_rx_fail_int_len 1
#define	eagle_reg_ep2_rx_fail_int_lsb 0
#define xd_p_eagle_reg_ep3_tx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep3_tx_fail_int	0xDD1A 
#define	eagle_reg_ep3_tx_fail_int_pos 4
#define	eagle_reg_ep3_tx_fail_int_len 1
#define	eagle_reg_ep3_tx_fail_int_lsb 0
#define xd_p_eagle_reg_ep5_tx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep5_tx_fail_int	0xDD1A 
#define	eagle_reg_ep5_tx_fail_int_pos 6
#define	eagle_reg_ep5_tx_fail_int_len 1
#define	eagle_reg_ep5_tx_fail_int_lsb 0
#define xd_p_eagle_reg_ep6_rx_fail_int	(*(volatile byte xdata *) 0xDD1A)
#define    p_eagle_reg_ep6_rx_fail_int	0xDD1A 
#define	eagle_reg_ep6_rx_fail_int_pos 7
#define	eagle_reg_ep6_rx_fail_int_len 1
#define	eagle_reg_ep6_rx_fail_int_lsb 0
#define xd_p_eagle_reg_suspend_int	(*(volatile byte xdata *) 0xDD1B)
#define    p_eagle_reg_suspend_int	0xDD1B 
#define	eagle_reg_suspend_int_pos 0
#define	eagle_reg_suspend_int_len 1
#define	eagle_reg_suspend_int_lsb 0
#define xd_p_eagle_reg_bus_reset_int	(*(volatile byte xdata *) 0xDD1B)
#define    p_eagle_reg_bus_reset_int	0xDD1B 
#define	eagle_reg_bus_reset_int_pos 1
#define	eagle_reg_bus_reset_int_len 1
#define	eagle_reg_bus_reset_int_lsb 0
#define xd_p_eagle_reg_ep0_setup_int	(*(volatile byte xdata *) 0xDD1B)
#define    p_eagle_reg_ep0_setup_int	0xDD1B 
#define	eagle_reg_ep0_setup_int_pos 2
#define	eagle_reg_ep0_setup_int_len 1
#define	eagle_reg_ep0_setup_int_lsb 0
#define xd_r_usbc_int	(*(volatile byte xdata *) 0xDD1B)
#define    r_usbc_int	0xDD1B 
#define	usbc_int_pos 3
#define	usbc_int_len 1
#define	usbc_int_lsb 0
#define xd_r_usb_ir_int	(*(volatile byte xdata *) 0xDD1B)
#define    r_usb_ir_int	0xDD1B 
#define	usb_ir_int_pos 4
#define	usb_ir_int_len 1
#define	usb_ir_int_lsb 0
#define xd_p_eagle_reg_ep0_tx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep0_tx_rst	0xDD1D 
#define	eagle_reg_ep0_tx_rst_pos 0
#define	eagle_reg_ep0_tx_rst_len 1
#define	eagle_reg_ep0_tx_rst_lsb 0
#define xd_p_eagle_reg_ep0_rx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep0_rx_rst	0xDD1D 
#define	eagle_reg_ep0_rx_rst_pos 1
#define	eagle_reg_ep0_rx_rst_len 1
#define	eagle_reg_ep0_rx_rst_lsb 0
#define xd_p_eagle_reg_ep1_tx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep1_tx_rst	0xDD1D 
#define	eagle_reg_ep1_tx_rst_pos 2
#define	eagle_reg_ep1_tx_rst_len 1
#define	eagle_reg_ep1_tx_rst_lsb 0
#define xd_p_eagle_reg_ep2_rx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep2_rx_rst	0xDD1D 
#define	eagle_reg_ep2_rx_rst_pos 3
#define	eagle_reg_ep2_rx_rst_len 1
#define	eagle_reg_ep2_rx_rst_lsb 0
#define xd_p_eagle_reg_ep3_tx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep3_tx_rst	0xDD1D 
#define	eagle_reg_ep3_tx_rst_pos 4
#define	eagle_reg_ep3_tx_rst_len 1
#define	eagle_reg_ep3_tx_rst_lsb 0
#define xd_p_eagle_reg_ep5_tx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep5_tx_rst	0xDD1D 
#define	eagle_reg_ep5_tx_rst_pos 6
#define	eagle_reg_ep5_tx_rst_len 1
#define	eagle_reg_ep5_tx_rst_lsb 0
#define xd_p_eagle_reg_ep6_rx_rst	(*(volatile byte xdata *) 0xDD1D)
#define    p_eagle_reg_ep6_rx_rst	0xDD1D 
#define	eagle_reg_ep6_rx_rst_pos 7
#define	eagle_reg_ep6_rx_rst_len 1
#define	eagle_reg_ep6_rx_rst_lsb 0
#define xd_r_eagle_reg_ep0_tx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep0_tx_active	0xDD1E 
#define	eagle_reg_ep0_tx_active_pos 0
#define	eagle_reg_ep0_tx_active_len 1
#define	eagle_reg_ep0_tx_active_lsb 0
#define xd_r_eagle_reg_ep0_rx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep0_rx_active	0xDD1E 
#define	eagle_reg_ep0_rx_active_pos 1
#define	eagle_reg_ep0_rx_active_len 1
#define	eagle_reg_ep0_rx_active_lsb 0
#define xd_r_eagle_reg_ep1_tx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep1_tx_active	0xDD1E 
#define	eagle_reg_ep1_tx_active_pos 2
#define	eagle_reg_ep1_tx_active_len 1
#define	eagle_reg_ep1_tx_active_lsb 0
#define xd_r_eagle_reg_ep2_rx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep2_rx_active	0xDD1E 
#define	eagle_reg_ep2_rx_active_pos 3
#define	eagle_reg_ep2_rx_active_len 1
#define	eagle_reg_ep2_rx_active_lsb 0
#define xd_r_eagle_reg_ep3_tx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep3_tx_active	0xDD1E 
#define	eagle_reg_ep3_tx_active_pos 4
#define	eagle_reg_ep3_tx_active_len 1
#define	eagle_reg_ep3_tx_active_lsb 0
#define xd_r_eagle_reg_ep5_tx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep5_tx_active	0xDD1E 
#define	eagle_reg_ep5_tx_active_pos 6
#define	eagle_reg_ep5_tx_active_len 1
#define	eagle_reg_ep5_tx_active_lsb 0
#define xd_r_eagle_reg_ep6_rx_active	(*(volatile byte xdata *) 0xDD1E)
#define    r_eagle_reg_ep6_rx_active	0xDD1E 
#define	eagle_reg_ep6_rx_active_pos 7
#define	eagle_reg_ep6_rx_active_len 1
#define	eagle_reg_ep6_rx_active_lsb 0
#define xd_p_eagle_reg_usb_setup_reset	(*(volatile byte xdata *) 0xDD1F)
#define    p_eagle_reg_usb_setup_reset	0xDD1F 
#define	eagle_reg_usb_setup_reset_pos 0
#define	eagle_reg_usb_setup_reset_len 1
#define	eagle_reg_usb_setup_reset_lsb 0
#define xd_p_eagle_reg_usb_ep5_retry_new	(*(volatile byte xdata *) 0xDD1F)
#define    p_eagle_reg_usb_ep5_retry_new	0xDD1F 
#define	eagle_reg_usb_ep5_retry_new_pos 2
#define	eagle_reg_usb_ep5_retry_new_len 1
#define	eagle_reg_usb_ep5_retry_new_lsb 0
#define xd_p_usb_ep6_empty	(*(volatile byte xdata *) 0xDD1F)
#define    p_usb_ep6_empty	0xDD1F 
#define	usb_ep6_empty_pos 3
#define	usb_ep6_empty_len 1
#define	usb_ep6_empty_lsb 0
#define xd_p_eagle_reg_ep5_tx_len_7_0	(*(volatile byte xdata *) 0xDD8A)
#define    p_eagle_reg_ep5_tx_len_7_0	0xDD8A 
#define	eagle_reg_ep5_tx_len_7_0_pos 0
#define	eagle_reg_ep5_tx_len_7_0_len 8
#define	eagle_reg_ep5_tx_len_7_0_lsb 0
#define xd_p_eagle_reg_ep5_tx_len_15_8	(*(volatile byte xdata *) 0xDD8B)
#define    p_eagle_reg_ep5_tx_len_15_8	0xDD8B 
#define	eagle_reg_ep5_tx_len_15_8_pos 0
#define	eagle_reg_ep5_tx_len_15_8_len 8
#define	eagle_reg_ep5_tx_len_15_8_lsb 8
#define xd_p_eagle_reg_ep6_cnt_num_7_0	(*(volatile byte xdata *) 0xDDA9)
#define    p_eagle_reg_ep6_cnt_num_7_0	0xDDA9 
#define	eagle_reg_ep6_cnt_num_7_0_pos 0
#define	eagle_reg_ep6_cnt_num_7_0_len 8
#define	eagle_reg_ep6_cnt_num_7_0_lsb 0

